---
development:
  cloud_name: isarovic
  api_key: '575163649548789'
  api_secret: 3CsrZ1gHpgm_URNg47_4wlQ9YOM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: isarovic
  api_key: '575163649548789'
  api_secret: 3CsrZ1gHpgm_URNg47_4wlQ9YOM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: isarovic
  api_key: '575163649548789'
  api_secret: 3CsrZ1gHpgm_URNg47_4wlQ9YOM
  enhance_image_tag: true
  static_image_support: false
